# Before your start:
- Read the README.md file
- Comment as much as you can and use the resources in the README.md file
- Happy learning!

In [1]:
# Import your libraries:
import pandas as pd
import numpy as np
from sklearn.datasets import load_diabetes

# Challenge 1 - Explore the Scikit-Learn Datasets

Before starting to work on our own datasets, let's first explore the datasets that are included in this Python library. These datasets have been cleaned and formatted for use in ML algorithms.

First, we will load the diabetes dataset. Do this in the cell below by importing the datasets and then loading the dataset  to the `diabetes` variable using the `load_diabetes()` function ([documentation](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_diabetes.html)).

In [2]:
# Your code here:
diabetes=load_diabetes()

Let's explore this variable by looking at the different attributes (keys) of `diabetes`. Note that the `load_diabetes` function does not return dataframes. It returns you a Python dictionary.

In [3]:
# Your code here:
diabetes

{'data': array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
          0.01990842, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
         -0.06832974, -0.09220405],
        [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
          0.00286377, -0.02593034],
        ...,
        [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
         -0.04687948,  0.01549073],
        [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
          0.04452837, -0.02593034],
        [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
         -0.00421986,  0.00306441]]),
 'target': array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
         69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
         68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
         87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
        259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
        128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
        150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
        200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
         42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
         83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
        104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
        173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
        107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
         60., 174., 259., 178., 128.,  96., 126., 288.,  88., 292.,  71.,
        197., 186.,  25.,  84.,  96., 195.,  53., 217., 172., 131., 214.,
         59.,  70., 220., 268., 152.,  47.,  74., 295., 101., 151., 127.,
        237., 225.,  81., 151., 107.,  64., 138., 185., 265., 101., 137.,
        143., 141.,  79., 292., 178.,  91., 116.,  86., 122.,  72., 129.,
        142.,  90., 158.,  39., 196., 222., 277.,  99., 196., 202., 155.,
         77., 191.,  70.,  73.,  49.,  65., 263., 248., 296., 214., 185.,
         78.,  93., 252., 150.,  77., 208.,  77., 108., 160.,  53., 220.,
        154., 259.,  90., 246., 124.,  67.,  72., 257., 262., 275., 177.,
         71.,  47., 187., 125.,  78.,  51., 258., 215., 303., 243.,  91.,
        150., 310., 153., 346.,  63.,  89.,  50.,  39., 103., 308., 116.,
        145.,  74.,  45., 115., 264.,  87., 202., 127., 182., 241.,  66.,
         94., 283.,  64., 102., 200., 265.,  94., 230., 181., 156., 233.,
         60., 219.,  80.,  68., 332., 248.,  84., 200.,  55.,  85.,  89.,
         31., 129.,  83., 275.,  65., 198., 236., 253., 124.,  44., 172.,
        114., 142., 109., 180., 144., 163., 147.,  97., 220., 190., 109.,
        191., 122., 230., 242., 248., 249., 192., 131., 237.,  78., 135.,
        244., 199., 270., 164.,  72.,  96., 306.,  91., 214.,  95., 216.,
        263., 178., 113., 200., 139., 139.,  88., 148.,  88., 243.,  71.,
         77., 109., 272.,  60.,  54., 221.,  90., 311., 281., 182., 321.,
         58., 262., 206., 233., 242., 123., 167.,  63., 197.,  71., 168.,
        140., 217., 121., 235., 245.,  40.,  52., 104., 132.,  88.,  69.,
        219.,  72., 201., 110.,  51., 277.,  63., 118.,  69., 273., 258.,
         43., 198., 242., 232., 175.,  93., 168., 275., 293., 281.,  72.,
        140., 189., 181., 209., 136., 261., 113., 131., 174., 257.,  55.,
         84.,  42., 146., 212., 233.,  91., 111., 152., 120.,  67., 310.,
         94., 183.,  66., 173.,  72.,  49.,  64.,  48., 178., 104., 132.,
        220.,  57.]),
 'DESCR': '.. _diabetes_dataset:\n\nDiabetes dataset\n----------------\n\nTen baseline variables, age, sex, body mass index, average blood\npressure, and six blood serum measurements were obtained for each of n =\n442 diabetes patients, as well as the response of interest, a\nquantitative measure of disease progression one year after baseline.\n\n**Data Set Characteristics:**\n\n  :Number of Instances: 442\n\n  :Number of Attributes: First 10 columns are numeric predictive values\n\n  :Target: Column 11 is a quantitative measure of disease progression one year after baseline\n\n  :Attribute Information:\n      - Age\n      - Sex\n      - Body mass index\n      - Average blood pressure\n      - S1\n      - S2\n      - S3\n      - S4\n      - S5\n      - S6\n\nNote: Each of these 10 feature variables have been mean centered and scaled by the standard deviation times `n_samples` (i.e. the sum of squares of each column totals 1).\n\nSource URL:\nhttps://www4.stat.ncsu.edu/~boos/var.select/diabetes.html\n\nFor more information see:\nBradley Efron, Trevor Hastie, Iain Johnstone and Robert Tibshirani (2004) "Least Angle Regression," Annals of Statistics (with discussion), 407-499.\n(https://web.stanford.edu/~hastie/Papers/LARS/LeastAngle_2002.pdf)',
 'feature_names': ['age',
  'sex',
  'bmi',
  'bp',
  's1',
  's2',
  's3',
  's4',
  's5',
  's6'],
 'data_filename': '/Users/claraFDEZ/miniconda3/envs/project/lib/python3.7/site-packages/sklearn/datasets/data/diabetes_data.csv.gz',
 'target_filename': '/Users/claraFDEZ/miniconda3/envs/project/lib/python3.7/site-packages/sklearn/datasets/data/diabetes_target.csv.gz'}

#### The next step is to read the description of the dataset. 

Print the description in the cell below using the `DESCR` attribute of the `diabetes` variable. Read the data description carefully to fully understand what each column represents.

*Hint: If your output is ill-formatted by displaying linebreaks as `\n`, it means you are not using the `print` function.*

In [4]:
# Your code here:
print(diabetes.DESCR)

.. _diabetes_dataset:

Diabetes dataset
----------------

Ten baseline variables, age, sex, body mass index, average blood
pressure, and six blood serum measurements were obtained for each of n =
442 diabetes patients, as well as the response of interest, a
quantitative measure of disease progression one year after baseline.

**Data Set Characteristics:**

  :Number of Instances: 442

  :Number of Attributes: First 10 columns are numeric predictive values

  :Target: Column 11 is a quantitative measure of disease progression one year after baseline

  :Attribute Information:
      - Age
      - Sex
      - Body mass index
      - Average blood pressure
      - S1
      - S2
      - S3
      - S4
      - S5
      - S6

Note: Each of these 10 feature variables have been mean centered and scaled by the standard deviation times `n_samples` (i.e. the sum of squares of each column totals 1).

Source URL:
https://www4.stat.ncsu.edu/~boos/var.select/diabetes.html

For more information see:
Bradley Efron, Trevor Hastie, Iain Johnstone and Robert Tibshirani (2004) "Least Angle Regression," Annals of Statistics (with discussion), 407-499.
(https://web.stanford.edu/~hastie/Papers/LARS/LeastAngle_2002.pdf)

#### Based on the data description, answer the following questions:

1. How many attributes are there in the data? What do they mean?

1. What is the relation between `diabetes['data']` and `diabetes['target']`?

1. How many records are there in the data?

# Enter your answer here:
# 1. 
there are 11 attributes, the mean is: Ten baseline variables, age, sex, body mass index, average blood pressure, and six blood serum measurements were obtained for each of n = 442 diabetes patients, as well as the response of interest, a
quantitative measure of disease progression one year after baseline.
# 3.
There are 442 records in data

#### Now explore what are contained in the *data* portion as well as the *target* portion of `diabetes`. 

Scikit-learn typically takes in 2D numpy arrays as input (though pandas dataframes are also accepted). Inspect the shape of `data` and `target`. Confirm they are consistent with the data description.

In [5]:
# Your code here:
diabetes.data

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990842, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06832974, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286377, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04687948,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452837, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00421986,  0.00306441]])

In [6]:
diabetes.target

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 288.,  88., 292.,  71.,
       197., 186.,  25.,  84.,  96., 195.,  53., 217., 172., 131., 214.,
        59.,  70., 220., 268., 152.,  47.,  74., 295., 101., 151., 127.,
       237., 225.,  81., 151., 107.,  64., 138., 185., 265., 101., 137.,
       143., 141.,  79., 292., 178.,  91., 116.,  86., 122.,  72., 129.,
       142.,  90., 158.,  39., 196., 222., 277.,  99., 196., 202., 155.,
        77., 191.,  70.,  73.,  49.,  65., 263., 248., 296., 214., 185.,
        78.,  93., 252., 150.,  77., 208.,  77., 108., 160.,  53., 220.,
       154., 259.,  90., 246., 124.,  67.,  72., 257., 262., 275., 177.,
        71.,  47., 187., 125.,  78.,  51., 258., 215., 303., 243.,  91.,
       150., 310., 153., 346.,  63.,  89.,  50.,  39., 103., 308., 116.,
       145.,  74.,  45., 115., 264.,  87., 202., 127., 182., 241.,  66.,
        94., 283.,  64., 102., 200., 265.,  94., 230., 181., 156., 233.,
        60., 219.,  80.,  68., 332., 248.,  84., 200.,  55.,  85.,  89.,
        31., 129.,  83., 275.,  65., 198., 236., 253., 124.,  44., 172.,
       114., 142., 109., 180., 144., 163., 147.,  97., 220., 190., 109.,
       191., 122., 230., 242., 248., 249., 192., 131., 237.,  78., 135.,
       244., 199., 270., 164.,  72.,  96., 306.,  91., 214.,  95., 216.,
       263., 178., 113., 200., 139., 139.,  88., 148.,  88., 243.,  71.,
        77., 109., 272.,  60.,  54., 221.,  90., 311., 281., 182., 321.,
        58., 262., 206., 233., 242., 123., 167.,  63., 197.,  71., 168.,
       140., 217., 121., 235., 245.,  40.,  52., 104., 132.,  88.,  69.,
       219.,  72., 201., 110.,  51., 277.,  63., 118.,  69., 273., 258.,
        43., 198., 242., 232., 175.,  93., 168., 275., 293., 281.,  72.,
       140., 189., 181., 209., 136., 261., 113., 131., 174., 257.,  55.,
        84.,  42., 146., 212., 233.,  91., 111., 152., 120.,  67., 310.,
        94., 183.,  66., 173.,  72.,  49.,  64.,  48., 178., 104., 132.,
       220.,  57.])

# Challenge 2 - Perform Supervised Learning on the Dataset

The data have already been split to predictor (*data*) and response (*target*) variables. Given this information, we'll apply what we have previously learned about linear regression and apply the algorithm to the diabetes dataset.

#### Let's briefly revisit the linear regression formula:

```
y = β0 + β1X1 + β2X2 + ... + βnXn + ϵ
```

...where:

- X1-Xn: data 
- β0: intercept 
- β1-βn: coefficients 
- ϵ: error (cannot explained by model)
- y: target

Also take a look at the `sklearn.linear_model.LinearRegression` [documentation](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html).

#### In the cell below, import the `linear_model` class from `sklearn`.

In [7]:
# Your code here:
from sklearn import linear_model
from sklearn.linear_model import LinearRegression

#### Create a new instance of the linear regression model and assign the new instance to the variable `diabetes_model`.

In [8]:
# Your code here:
X=diabetes.data
y=diabetes.target
diabetes_model=LinearRegression().fit(X, y)

#### Next, let's split the training and test data.

Define `diabetes_data_train`, `diabetes_target_train`, `diabetes_data_test`, and `diabetes_target_test`. Use the last 20 records for the test data and the rest for the training data.

In [9]:
# Your code here:
diabetes_data_train=X[:-20]
diabetes_data_test=X[-20:]
diabetes_target_train=y[:-20]
diabetes_target_test=y[-20:]

Fit the training data and target to `diabetes_model`. Print the *intercept* and *coefficients* of the model.

In [10]:
# Your code here:
diabetes_model.coef_

array([ -10.01219782, -239.81908937,  519.83978679,  324.39042769,
       -792.18416163,  476.74583782,  101.04457032,  177.06417623,
        751.27932109,   67.62538639])

In [11]:
diabetes_model.intercept_

152.1334841628965

#### Inspecting the results

From the outputs you should have seen:

- The intercept is a float number.
- The coefficients are an array containing 10 float numbers.

This is the linear regression model fitted to your training dataset.

#### Using your fitted linear regression model, predict the *y* of `diabetes_data_test`.

In [12]:
# Your code here:
diabetes_model.predict(diabetes_data_test)

array([199.27952034, 153.63210613, 171.80130949, 112.11314588,
       162.60650576, 129.8448476 , 258.02898298, 100.70869427,
       115.87611124, 122.53790409, 218.17749233,  60.94590955,
       131.09513588, 119.48417359,  52.60848094, 193.01802803,
       101.05169913, 121.22505534, 211.8588945 ,  53.44819015])

#### Print your `diabetes_target_test` and compare with the prediction.

In [13]:
# Your code here:
diabetes_target_test

array([233.,  91., 111., 152., 120.,  67., 310.,  94., 183.,  66., 173.,
        72.,  49.,  64.,  48., 178., 104., 132., 220.,  57.])

#### Is `diabetes_target_test` exactly the same as the model prediction? Explain.

# Your explanation here:
Isn't exactly the same

# Bonus Challenge 1 - Hypothesis Testing with `statsmodels`

After generating the linear regression model from the dataset, you probably wonder: then what? What is the statistical way to know if my model is reliable or not?

Good question. We'll discuss that using Scikit-Learn in Challenge 5. But for now, let's use a fool-proof way by using the ([Linear Regression class of StatsModels](https://www.statsmodels.org/dev/regression.html)) which can also conduct linear regression analysis plus much more such as calcuating the F-score of the linear model as well as the standard errors and t-scores for each coefficient. The F-score and t-scores will tell you whether you can trust your linear model.

To understand the statistical meaning of conducting hypothesis testing (e.g. F-test, t-test) for slopes, read [this webpage](https://onlinecourses.science.psu.edu/stat501/node/297/) at your leisure time. We'll give you a brief overview next.

* The F-test of your linear model is to verify whether at least one of your coefficients is significantly different from zero. Translating that into the *null hypothesis* and *alternative hypothesis*, that is:

    ```
    H0 : β1 = β2 = ... = β10 = 0
    HA : At least one βj ≠ 0 (for j = 1, 2, ..., 10)
    ```

* The t-tests on each coefficient is to check whether the confidence interval for the variable contains zero. If the confidence interval contains zero, it means the null hypothesis for that variable is not rejected. In other words, this particular vaiable is not contributing to your linear model and you can remove it from your formula.

Read the documentations of [StatsModels Linear Regression](https://www.statsmodels.org/dev/regression.html) as well as its [`OLS` class](https://www.statsmodels.org/dev/generated/statsmodels.regression.linear_model.OLS.html) which stands for *ordinary least squares*.

#### In the next cell, analyze `diabetes_data_train` and `diabetes_target_train` with the linear regression model of `statsmodels`. Print the fit summary.

Your output should look like:

![statsmodels regression](../statsmodels.png)

In [14]:
# Your code here:
import statsmodels.api as sm
mod = sm.OLS(diabetes_target_train, diabetes_data_train)
res = mod.fit()
print(res.summary())

                                 OLS Regression Results
=======================================================================================
Dep. Variable:                      y   R-squared (uncentered):                   0.110
Model:                            OLS   Adj. R-squared (uncentered):              0.089
Method:                 Least Squares   F-statistic:                              5.109
Date:                Wed, 24 Jul 2019   Prob (F-statistic):                    4.77e-07
Time:                        21:29:08   Log-Likelihood:                         -2745.5
No. Observations:                 422   AIC:                                      5511.
Df Residuals:                     412   BIC:                                      5552.
Df Model:                          10
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1            42.9190    183.983      0.233      0.816    -318.744     404.582
x2          -261.9605    188.650     -1.389      0.166    -632.798     108.877
x3           547.5378    204.613      2.676      0.008     145.322     949.754
x4           352.4704    200.777      1.756      0.080     -42.205     747.146
x5          -634.0265   1273.063     -0.498      0.619   -3136.536    1868.483
x6           285.1002   1033.408      0.276      0.783   -1746.310    2316.510
x7            -9.4062    658.863     -0.014      0.989   -1304.558    1285.746
x8           197.4998    502.388      0.393      0.694    -790.064    1185.063
x9           670.7500    526.463      1.274      0.203    -364.139    1705.639
x10           11.6643    205.008      0.057      0.955    -391.327     414.656
==============================================================================
Omnibus:                        0.574   Durbin-Watson:                   0.228
Prob(Omnibus):                  0.751   Jarque-Bera (JB):                0.677
Skew:                          -0.001   Prob(JB):                        0.713
Kurtosis:                       2.804   Cond. No.                         21.4
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

#### Interpreting hypothesis testing results

Answer the following questions in the cell below:

1. What is the F-score of your linear model and is the null hypothesis rejected?

1. Does any of the t-tests of the coefficients produce a confidence interval containing zero? What are they?

1. How will you modify your linear reguression model according to the test results above?

In [15]:
# Your answers here:

# Challenge 3 - Peform Supervised Learning on a Pandas Dataframe

Now that we have dealt with data that has been formatted for scikit-learn, let's look at data that we will need to format ourselves.

In the next cell, load the `auto-mpg.csv` file included in this folder and assign it to a variable called `auto`.

In [16]:
# Your code here:
auto=pd.read_csv('../auto-mpg.csv')

Look at the first 5 rows using the `head()` function:

In [17]:
# Your code here:
auto.head()

,mpg,cylinders,displacement,horse_power,weight,acceleration,model_year,car_name
0,18.0,8,307.0,130.0,3504,12.0,70,"\t""chevrolet chevelle malibu"""
1,15.0,8,350.0,165.0,3693,11.5,70,"\t""buick skylark 320"""
2,18.0,8,318.0,150.0,3436,11.0,70,"\t""plymouth satellite"""
3,16.0,8,304.0,150.0,3433,12.0,70,"\t""amc rebel sst"""
4,17.0,8,302.0,140.0,3449,10.5,70,"\t""ford torino"""

Evaluate the data to ensure that all numeric columns are correctly detected as such by pandas. If a column is misclassified as object, coerce it to numeric.

In [18]:
# Your code here:
auto.dtypes

mpg             float64
cylinders         int64
displacement    float64
horse_power     float64
weight            int64
acceleration    float64
model_year        int64
car_name         object
dtype: object

What is the newest model year and the oldest model year?

In [19]:
# Your code here:
newest_model=auto.sort_values(by=['model_year'],ascending=False)
oldest_model=auto.sort_values(by=['model_year'])
newest_model.head(1)

,mpg,cylinders,displacement,horse_power,weight,acceleration,model_year,car_name
397,31.0,4,119.0,82.0,2720,19.4,82,"\t""chevy s-10"""

In [20]:
oldest_model.head(1)

,mpg,cylinders,displacement,horse_power,weight,acceleration,model_year,car_name
0,18.0,8,307.0,130.0,3504,12.0,70,"\t""chevrolet chevelle malibu"""

Check the dataset for missing values and remove all rows containing at least one missing value.

In [21]:
# Your code here:
auto.isnull().sum()

mpg             0
cylinders       0
displacement    0
horse_power     6
weight          0
acceleration    0
model_year      0
car_name        0
dtype: int64

In [22]:
auto=auto.dropna()
auto.isnull().sum()

mpg             0
cylinders       0
displacement    0
horse_power     0
weight          0
acceleration    0
model_year      0
car_name        0
dtype: int64

Find the frequency table for the `cylinders` column using the `value_counts()` function. How many possible values of cylinders are there?

In [23]:
# Your code here:
auto['cylinders'].value_counts()

4    199
8    103
6     83
3      4
5      3
Name: cylinders, dtype: int64

We would like to generate a linear regression model that will predict mpg. To do this, first drop the `car_name` column since it does not contain any quantitative data. Next separate the dataframe to predictor and response variables. Separate those into test and training data with 80% of the data in the training set and the remainder in the test set. 

Assign the predictor and response training data to `X_train` and `y_train` respectively. Similarly, assign the predictor and response test data to `X_test` and `y_test`.

*Hint: To separate data for training and test, use the `train_test_split` method we used in previous labs.*

In [24]:
# Your code here:
auto.drop(columns=['car_name'], inplace=True)

In [25]:
from sklearn.model_selection import train_test_split
X=auto[['cylinders','displacement','horse_power','weight','acceleration', 'model_year']]
y=auto['mpg']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [26]:
X_train

     cylinders  displacement  horse_power  weight  acceleration  model_year
332          4          89.0         62.0    1845          15.3          80
112          4         122.0         85.0    2310          18.5          73
350          4         105.0         63.0    2215          14.9          81
0            8         307.0        130.0    3504          12.0          70
82           4         120.0         97.0    2506          14.5          72
269          4         105.0         75.0    2230          14.5          78
259          6         200.0         85.0    3070          16.7          78
319          4         120.0         75.0    2542          17.5          80
308          4         151.0         90.0    2556          13.2          79
22           4         104.0         95.0    2375          17.5          70
387          6         262.0         85.0    3015          17.0          82
186          4         101.0         83.0    2202          15.3          76
306          6         173.0        115.0    2595          11.3          79
248          4          91.0         60.0    1800          16.4          78
264          8         302.0        139.0    3205          11.2          78
339          4         151.0         84.0    2635          16.4          81
166          8         302.0        129.0    3169          12.0          75
258          6         231.0        105.0    3380          15.8          78
75           8         318.0        150.0    4077          14.0          72
280          6         231.0        115.0    3245          15.4          79
266          4          98.0         68.0    2155          16.5          78
90           8         429.0        198.0    4952          11.5          73
250          8         318.0        140.0    3735          13.2          78
324          4          85.0         65.0    2110          19.2          80
144          4          76.0         52.0    1649          16.5          74
30           4         140.0         90.0    2264          15.5          71
38           8         350.0        165.0    4209          12.0          71
359          4         141.0         80.0    3230          20.4          81
331          4          97.0         67.0    2145          18.0          80
74           8         302.0        140.0    4294          16.0          72
..         ...           ...          ...     ...           ...         ...
322          4          86.0         65.0    2110          17.9          80
146          4          90.0         75.0    2125          14.5          74
217          4         111.0         80.0    2155          14.8          77
136          8         302.0        140.0    4141          14.0          74
113          6         155.0        107.0    2472          14.0          73
98           6         250.0        100.0    3278          18.0          73
206          4         140.0         72.0    2565          13.6          76
183          4         116.0         81.0    2220          16.9          76
221          8         305.0        145.0    3880          12.5          77
199          6         225.0        100.0    3651          17.7          76
200          6         250.0         78.0    3574          21.0          76
92           8         351.0        158.0    4363          13.0          73
57           4         113.0         95.0    2278          15.5          72
241          6         146.0         97.0    2815          14.5          77
123          6         156.0        122.0    2807          13.5          73
369          4         112.0         88.0    2395          18.0          82
84           4          97.0         88.0    2100          16.5          72
10           8         383.0        170.0    3563          10.0          70
21           4         107.0         90.0    2430          14.5          70
41           8         318.0        150.0    4096          13.0          71
383          4          91.0         67.0    1965          15.0          82
363          6         231.0        110.0    3415          15.8          81
39           8         400.0        175.0    4464          11.5          71
116          8         400.0        230.0    4278           9.5          73
281          6         200.0         85.0    2990          18.2          79
299          4         141.0         71.0    3190          24.8          79
177          4         115.0         95.0    2694          15.0          75
278          4          89.0         71.0    1990          14.9          78
24           6         199.0         90.0    2648          15.0          70
335          4         122.0         88.0    2500          15.1          80

[313 rows x 6 columns]

Now we will processed and peform linear regression on this data to predict the mpg for each vehicle. 

#### In the next cell, create an instance of the linear regression model and call it `auto_model`. Fit `auto_model` with your training data.

In [27]:
# Your code here:
auto_model = LinearRegression().fit(X, y)

# Challenge 4 - Evaluate the Model

In addition to evaluating your model with F-test and t-test, you can also use the *Coefficient of Determination* (a.k.a. *r squared score*). This method does not simply tell *yes* or *no* about the model fit but instead indicates how much variation can be explained by the model. Based on the r squared score, you can decide whether to improve your model in order to obtain a better fit.

You can learn about the r squared score [here](). Its formula is:

![R Squared](../r-squared.png)

...where:

* yi is an actual data point.
* ŷi is the corresponding data point on the estimated regression line.

By adding the squares of the difference between all yi-ŷi pairs, we have a measure called SSE (*error sum of squares*) which is an application of the r squared score to indicate the extent to which the estimated regression model is different from the actual data. And we attribute that difference to the random error that is unavoidable in the real world. Obviously, we want the SSE value to be as small as possible.

#### In the next cell, compute the predicted *y* based on `X_train` and call it `y_pred`. Then calcualte the r squared score between `y_pred` and `y_train` which indicates how well the estimated regression model fits the training data.

*Hint: r squared score can be calculated using `sklearn.metrics.r2_score` ([documentation](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.r2_score.html)).*

In [28]:
from sklearn.metrics import r2_score

In [29]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((313, 6), (79, 6), (313,), (79,))

In [30]:
X_train

     cylinders  displacement  horse_power  weight  acceleration  model_year
332          4          89.0         62.0    1845          15.3          80
112          4         122.0         85.0    2310          18.5          73
350          4         105.0         63.0    2215          14.9          81
0            8         307.0        130.0    3504          12.0          70
82           4         120.0         97.0    2506          14.5          72
269          4         105.0         75.0    2230          14.5          78
259          6         200.0         85.0    3070          16.7          78
319          4         120.0         75.0    2542          17.5          80
308          4         151.0         90.0    2556          13.2          79
22           4         104.0         95.0    2375          17.5          70
387          6         262.0         85.0    3015          17.0          82
186          4         101.0         83.0    2202          15.3          76
306          6         173.0        115.0    2595          11.3          79
248          4          91.0         60.0    1800          16.4          78
264          8         302.0        139.0    3205          11.2          78
339          4         151.0         84.0    2635          16.4          81
166          8         302.0        129.0    3169          12.0          75
258          6         231.0        105.0    3380          15.8          78
75           8         318.0        150.0    4077          14.0          72
280          6         231.0        115.0    3245          15.4          79
266          4          98.0         68.0    2155          16.5          78
90           8         429.0        198.0    4952          11.5          73
250          8         318.0        140.0    3735          13.2          78
324          4          85.0         65.0    2110          19.2          80
144          4          76.0         52.0    1649          16.5          74
30           4         140.0         90.0    2264          15.5          71
38           8         350.0        165.0    4209          12.0          71
359          4         141.0         80.0    3230          20.4          81
331          4          97.0         67.0    2145          18.0          80
74           8         302.0        140.0    4294          16.0          72
..         ...           ...          ...     ...           ...         ...
322          4          86.0         65.0    2110          17.9          80
146          4          90.0         75.0    2125          14.5          74
217          4         111.0         80.0    2155          14.8          77
136          8         302.0        140.0    4141          14.0          74
113          6         155.0        107.0    2472          14.0          73
98           6         250.0        100.0    3278          18.0          73
206          4         140.0         72.0    2565          13.6          76
183          4         116.0         81.0    2220          16.9          76
221          8         305.0        145.0    3880          12.5          77
199          6         225.0        100.0    3651          17.7          76
200          6         250.0         78.0    3574          21.0          76
92           8         351.0        158.0    4363          13.0          73
57           4         113.0         95.0    2278          15.5          72
241          6         146.0         97.0    2815          14.5          77
123          6         156.0        122.0    2807          13.5          73
369          4         112.0         88.0    2395          18.0          82
84           4          97.0         88.0    2100          16.5          72
10           8         383.0        170.0    3563          10.0          70
21           4         107.0         90.0    2430          14.5          70
41           8         318.0        150.0    4096          13.0          71
383          4          91.0         67.0    1965          15.0          82
363          6         231.0        110.0    3415          15.8          81
39           8         400.0        175.0    4464          11.5          71
116          8         400.0        230.0    4278           9.5          73
281          6         200.0         85.0    2990          18.2          79
299          4         141.0         71.0    3190          24.8          79
177          4         115.0         95.0    2694          15.0          75
278          4          89.0         71.0    1990          14.9          78
24           6         199.0         90.0    2648          15.0          70
335          4         122.0         88.0    2500          15.1          80

[313 rows x 6 columns]

In [31]:
# Your code here:
y_pred=auto_model.predict(X_train)
r2_score(y_train, y_pred)

0.8007056653525783

#### Our next step is to evaluate the model using the test data. 

We would like to ensure that our model is not overfitting the data. This means that our model was made to fit too closely to the training data by being overly complex. If a model is overfitted, it is not generalizable to data outside the training data. In that case, we need to reduce the complexity of the model by removing certain features (variables).

In the cell below, use the model to generate the predicted values for the test data and assign them to `y_test_pred`. Compute the r squared score of the predicted `y_test_pred` and the oberserved `y_test` data.

In [32]:
# Your code here:
y_test_pred=auto_model.predict(X_test)
r2_score(y_test, y_test_pred)

0.8372635161076709

#### Explaining the results

The r squared scores of the training data and the test data are pretty close (0.8146 vs 0.7818). This means our model is not overfitted. However, there is still room to improve the model fit. Move on to the next challenge.

# Challenge 5 - Improve the Model Fit

While the most common way to improve the fit of a model is by using [regularization](https://datanice.github.io/machine-learning-101-what-is-regularization-interactive.html), there are other simpler ways to improve model fit. The first is to create a simpler model. The second is to increase the train sample size.

Let us start with the easier option and increase our train sample size to 90% of the data. Create a new test train split and name the new predictors and response variables `X_train09`, `X_test09`, `y_train09`, `y_test09`.

In [33]:
# Your code here:
X_train09, X_test09, y_train09, y_test09= train_test_split(X, y, test_size=0.1)

Initialize a new linear regression model. Name this model `auto_model09`. Fit the model to the new sample (training) data.

In [34]:
# Your code here:
auto_model09=LinearRegression().fit(X, y)

Compute the predicted values and r squared score for our new model and new sample data.

In [35]:
# Your code here:
y_pred09=auto_model.predict(X_train09)
r2_score(y_train09, y_pred09)

0.8033026936255575

Compute the r squared score for the smaller test set. Is there an improvement in the test r squared?

In [36]:
# Your code here:
y_test_pred09=auto_model.predict(X_test09)
r2_score(y_test09, y_test_pred09)

0.8661656491864649

# Bonus Challenge 2 - Backward Elimination 

The main way to produce a simpler linear regression model is to reduce the number of variables used in the model. In scikit-learn, we can do this by using recursive feature elimination. You can read more about RFE [here](https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.RFE.html).

In the next cell, we will import RFE

In [37]:
from sklearn.feature_selection import RFE

Follow the documentation and initialize an RFE model using the `auto_model` linear regression model. Set `n_features_to_select=3`

In [38]:
# Your code here:
selector = RFE(auto_model, n_features_to_select=3, step=1)
selector = selector.fit(X, y)

Fit the model and print the ranking

In [39]:
# Your code here:
selector = selector.fit(X, y)
selector.ranking_

array([1, 2, 4, 3, 1, 1])

In [40]:
columnas_buenas=selector.support_
columnas_buenas

array([ True, False, False, False,  True,  True])

Feature importance is ranked from most important (1) to least important (4). Generate a model with the three most important features. The features correspond to variable names. For example, feature 1 is `cylinders` and feature 2 is `displacement`.

Perform a test-train split on this reduced column data and call the split data `X_train_reduced`, `X_test_reduced`, `y_test_reduced`, `y_train_reduced`. Use an 80% split.

In [43]:
# Your code here:
X_train1=X_train[X_train.columns[columnas_buenas]]
X_train1.head()

     cylinders  acceleration  model_year
332          4          15.3          80
112          4          18.5          73
350          4          14.9          81
0            8          12.0          70
82           4          14.5          72

Generate a new model called `auto_model_reduced` and fit this model. Then proceed to compute the r squared score for the model. Did this cause an improvement in the r squared score?

In [46]:
# Your code here: 
X=auto[['cylinders','acceleration', 'model_year']]
y=auto['mpg']

X_train1, X_test1, y_train1, y_test1 = train_test_split(X, y, test_size=0.2)
auto_model_reduced= LinearRegression().fit(X, y)
y_pred1=auto_model.predict(X_train1)
r2_score(y_train1, y_pred1)

ValueError: shapes (313,3) and (6,) not aligned: 3 (dim 1) != 6 (dim 0)

#### Conclusion

You may obtain the impression from this lab that without knowing statistical methods in depth, it is difficult to make major progress in machine learning. That is correct. If you are motivated to become a data scientist, statistics is the subject you must be proficient in and there is no shortcut. 

Completing these labs is not likely to make you a data scientist. But you will have a good sense about what are there in machine learning and what are good for you. In your future career, you can choose one of the three tracks:

* Data scientists who need to be proficient in statistical methods.

* Data engineers who need to be good at programming.

* Data integration specialists who are business or content experts but also understand data and programming. This cross-disciplinary track brings together data, technology, and business and will be in high demands in the next decade.